### ISSUE TITLE
Create a method to update parameters in  rhc config files

### ISSUE THREAD

**Issue by Archana-PandeyM** [ptoscano/pytest-client-tools#18]
RHC has two config files- /etc/rhc/config.toml and /etc/rhc/workers/rhc-package-manager.toml
We need a method to change/update values in these toml files.
Example log-level="trace"

**Comment by ptoscano** [comment]
Strictly speaking, since they are TOML files, it is easy to edit them using the `toml` library:
```python
file = pathlib.Path("/etc/rhc/config.toml")
config = toml.loads(config_file.read_text())
config["broker"] = "ws://..."
file.write_text(toml.dumps(config))
```
What's the exact use case for some kind of abstraction on this?

As for `/etc/rhc/config.toml` and the mentioned `log-level`: this was something to do anyway, as the logging of `subscription-manager` is already configured to be `DEBUG`. I just pushed a change so that the `rhc` fixture already configures `log-level=trace`.

**Comment by Archana-PandeyM** [comment]
UseCase: to be able to have debug logs in case a test fails on rhcd or package-manager. basic logs are not enough for troubleshooting

**Comment by Archana-PandeyM** [comment]
I saw your PR which is already merged to change log level to trace for rhc.config. We need to do to the same for package-manager as well(/etc/rhc/workers/rhc-package-manager.toml):

Also I would like to highlight that the merged PR to update logs would fail upstream with "FileNotFound" error because upstream the package name is yggdrasil and config file is yggdrasil.config

**Comment by Archana-PandeyM** [comment]
Error in upstream tests:
save_rhc_files = None
test_config = <pytest_client_tools.test_config.TestConfig object at 0x7f43a27c9630>

    @pytest.fixture
    def rhc(save_rhc_files, test_config):
        rhc = Rhc()
        config_file = pathlib.Path("/etc/rhc/config.toml")
        try:
>           config = toml.loads(config_file.read_text())

venv/lib64/python3.6/site-packages/pytest_client_tools/plugin.py:232: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.6/pathlib.py:1196: in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
/usr/lib64/python3.6/pathlib.py:1183: in open
    opener=self._opener)
/usr/lib64/python3.6/pathlib.py:1037: in _opener
    return self._accessor.open(self, flags, mode)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pathobj = PosixPath('/etc/rhc/config.toml'), args = (524288, 438)

    @functools.wraps(strfunc)
    def wrapped(pathobj, *args):
>       return strfunc(str(pathobj), *args)
E       FileNotFoundError: [Errno 2] No such file or directory: '/etc/rhc/config.toml'

**Comment by Archana-PandeyM** [comment]
> I saw your PR which is already merged to change log level to trace for rhc.config. We need to do to the same for package-manager as well(/etc/rhc/workers/rhc-package-manager.toml):
> 
> Also I would like to highlight that the merged PR to update logs would fail upstream with "FileNotFound" error because upstream the package name is yggdrasil and config file is yggdrasil.config

Typo - yggdrasil.config is inconnect, correct path is /etc/yggdrasil/config.toml
